title: JL Christian

logo: assets/fonts/img/jlc-avatar.png
description: Fine Artist | Art Curator

google_analytics:
theme: jekyll-theme-minimal
environment:
  TEXT_SIZE: "08pt"
  FONT_FAMILY: "Arial"
